#format()方法的格式控制
s=["python,love,u","123"]
print("s={0:*^30}".format(s[0]))
#0指的是字符串的第一个，：是引导符号，*是填充物，^是居中方式，30是宽度
#先确定填充物，决定居中方式，在选择宽度
a=123.456
print("a={0:.2f}".format(a))
a=int(a)
print("a={0:x}".format(a))#x是16进制
print("a={0:o}".format(a))#x是8进制